/* SPDX-License-Identifier: GPL-2.0-or-later */
// Copyright (C) 2022-2026 Analog Devices, Inc.

#ifndef ADSP218XX_H
#define ADSP218XX_H

enum FLASH_COMMANDS {
	READ_COMMAND = 1,
	PROGRAM_COMMAND = 2,
	LOCK_COMMAND = 3,
	MASS_ERASE_COMMAND = 4,
	SECTOR_ERASE_COMMAND = 5,
	READ_ID_CODE_COMMAND = 6,
	EMMC_FILL = 7,
	EMMC_RESET = 8,
	EMMC_USER_AREA_MODE = 9,
	EMMC_BOOT_AREA_MODE = 10,
	EMMC_BOOT_AREA_ONE_ENABLE = 11,
	EMMC_BOOT_AREA_ONE_DISABLE = 12,
	EMMC_BOOT_BUS_WIDTH_EIGHT = 13,
	EMMC_BOOT_BUS_WIDTH_FOUR = 14,
	EMMC_BOOT_BUS_WIDTH_ONE = 15,
};

#endif // ADSP218XX_H
