name: checkpatch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkpatch:
    # The type of runner that the job will run on
    runs-on: [ self-hosted, btm-ci ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          # Update the submodules below, doing so here will convert ssh to https
          submodules: false

      - name: checkpatch
        run: |
          git diff remotes/origin/master > diff.patch
          tools/scripts/checkpatch.pl --max-line-length=200 --no-signoff --mailback -v --ignore MACRO_ARG_REUSE --ignore UNNECESSARY_PARENTHESES diff.patch
